### ISSUE TITLE
Index was outside the bounds of the array error

### ISSUE THREAD

**Issue by AlexDoubleU** [Civil-Cucumber/TradingViewDataAssembler_Public#2]
Getting [this error](https://i.imgur.com/V5vYQ8m.png) when trying to import the data. 

These are the files it's been given.

[paper-trading-history-all-2023-08-10T16 54 53.452Z.csv](https://github.com/Civil-Cucumber/TradingViewDataAssembler_Public/files/12329395/paper-trading-history-all-2023-08-10T16.54.53.452Z.csv)
[paper-trading-positions-2023-08-10T16 54 46.811Z.csv](https://github.com/Civil-Cucumber/TradingViewDataAssembler_Public/files/12329396/paper-trading-positions-2023-08-10T16.54.46.811Z.csv)

**Comment by Civil-Cucumber** [comment]
It should be fixed now in version 1.3: https://github.com/Civil-Cucumber/TradingViewDataAssembler_Public/releases/tag/v1.3.0

The problem was, that the symbol between hours, minutes and seconds was different for you (you had ".", I have "_").
